../rtl/altera_mf.v
../rtl/bank64k.v
../rtl/bram16k.v
../rtl/bram2m.v
../rtl/bram64k.v
../rtl/cdru.v
../rtl/cdwu.v
../rtl/maxpool.v
../rtl/mvp.v
../rtl/mvu.v
../rtl/shacc.v
../rtl/vvp.v
../rtl/interconn.v
../rtl/toplevel.v
../tb/utils.sv
../tb/top_tester.sv
