
../../../../../xilinx_proj/lowprecision/lowprecision.srcs/sources_1/ip/bram64k_xilinx/simulation/blk_mem_gen_v8_4.v
../../../../../xilinx_proj/lowprecision/lowprecision.srcs/sources_1/ip/bram64k_64x1024_xilinx/sim/bram64k_64x1024_xilinx.v
../../../../../xilinx_proj/lowprecision/lowprecision.srcs/sources_1/ip/bram2m_xilinx/simulation/blk_mem_gen_v8_4.v
../../../../../xilinx_proj/lowprecision/lowprecision.srcs/sources_1/ip/bram2m_xilinx/sim/bram2m_xilinx.v
../../3RD_PARTY_IP/rtl/altera_mf.v
../../../../verilog/bram64k.v
../../../../verilog/bank64k.v
../../../../verilog/bram2m.v
../../../../verilog/cdru.v
../../../../verilog/cdwu.v
../../../../verilog/maxpool.v
../../../../verilog/mvp.v
../../../../verilog/mvu.v
../../../../verilog/shacc.v
../../../../verilog/vvp.v
../../../../verilog/interconn.v
../../../../verilog/quantser.v
../../../../verilog/mvutop.v
../../../lib/utils/utils.sv
../tb/mvutop_tester.sv
